### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by RichCarne**
Propose using the OGC licence

### CODE REVIEW

**Comment by RichCarne** [comment]
Still looking for input on the choice of licence for weather on the web. Any thought @greg @chris ?

**Comment by gbuehler** [comment]
Rich, 

As this is done under the purview of OGC, I would assume that it should carry the same license that all OGC work carry. I have cc'd Jeff Burnett, Scott Simmons and Scott Serich, as I am not the definitive expert on such matters. Hopefully that can comment on this. 

Here is a copy of the OGC license text: 

=== 
*LICENSE AGREEMENT* 

[small]#Permission is hereby granted by the Open Geospatial Consortium, ("Licensor"), free of charge and subject to the terms set forth below, to any person obtaining a copy of this Intellectual Property and any associated documentation, to deal in the Intellectual Property without restriction (except as set forth below), including without limitation the rights to implement, use, copy, modify, merge, publish, distribute, and/or sublicense copies of the Intellectual Property, and to permit persons to whom the Intellectual Property is furnished to do so, provided that all copyright notices on the intellectual property are retained intact and that each person to whom the Intellectual Property is furnished agrees to the terms of this Agreement.# 

[small]#If you modify the Intellectual Property, all copies of the modified Intellectual Property must include, in addition to the above copyright notice, a notice that the Intellectual Property includes modifications that have not been approved or adopted by LICENSOR.# 

[small]#THIS LICENSE IS A COPYRIGHT LICENSE ONLY, AND DOES NOT CONVEY ANY RIGHTS UNDER ANY PATENTS THAT MAY BE IN FORCE ANYWHERE IN THE WORLD. THE INTELLECTUAL PROPERTY IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT OF THIRD PARTY RIGHTS. THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE DO NOT WARRANT THAT THE FUNCTIONS CONTAINED IN THE INTELLECTUAL PROPERTY WILL MEET YOUR REQUIREMENTS OR THAT THE OPERATION OF THE INTELLECTUAL PROPERTY WILL BE UNINTERRUPTED OR ERROR FREE. ANY USE OF THE INTELLECTUAL PROPERTY SHALL BE MADE ENTIRELY AT THE USER’S OWN RISK. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR ANY CONTRIBUTOR OF INTELLECTUAL PROPERTY RIGHTS TO THE INTELLECTUAL PROPERTY BE LIABLE FOR ANY CLAIM, OR ANY DIRECT, SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING FROM ANY ALLEGED INFRINGEMENT OR ANY LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR UNDER ANY OTHER LEGAL THEORY, ARISING OUT OF OR IN CONNECTION WITH THE IMPLEMENTATION, USE, COMMERCIALIZATION OR PERFORMANCE OF THIS INTELLECTUAL PROPERTY.# 

[small]#This license is effective until terminated. You may terminate it at any time by destroying the Intellectual Property together with all copies in any form. The license will also terminate if you fail to comply with any term or condition of this Agreement. Except as provided in the following sentence, no such termination of this license shall require the termination of any third party end-user sublicense to the Intellectual Property which is in force as of the date of notice of such termination. In addition, should the Intellectual Property, or the operation of the Intellectual Property, infringe, or in LICENSOR’s sole opinion be likely to infringe, any patent, copyright, trademark or other right of a third party, you agree that LICENSOR, in its sole discretion, may terminate this license without any compensation or liability to you, your licensees or any other party. You agree upon termination of any kind to destroy or cause to be destroyed the Intellectual Property together with all copies in any form, whether held by you or by any third party.# 

[small]#Except as contained in this notice, the name of LICENSOR or of any other holder of a copyright in all or part of the Intellectual Property shall not be used in advertising or otherwise to promote the sale, use or other dealings in this Intellectual Property without prior written authorization of LICENSOR or such copyright holder. LICENSOR is and shall at all times be the sole entity that may authorize you or any third party to use certification marks, trademarks or other special designations to indicate compliance with any LICENSOR standards or specifications.# 

[small]#This Agreement is governed by the laws of the Commonwealth of Massachusetts. The application to this Agreement of the United Nations Convention on Contracts for the International Sale of Goods is hereby expressly excluded. In the event any provision of this Agreement shall be deemed unenforceable, void or invalid, such provision shall be modified so as to make it valid and enforceable, and as so modified the entire Agreement shall remain in full force and effect. No decision, action or inaction by LICENSOR shall be construed to be a waiver of any rights or remedies available to it.# 

[small]#None of the Intellectual Property or underlying information or technology may be downloaded or otherwise exported or reexported in violation of U.S. export laws and regulations. In addition, you are responsible for complying with any local laws in your jurisdiction which may impact your right to import, export or use the Intellectual Property, and you represent that you have complied with any regulations or registration procedures required by applicable law to make this license enforceable.# 
=== 

__________________________________________ 

Greg Buehler 
Director, Outreach and Communication Services 
Open Geospatial Consortium (OGC) 
OGC: Making location count. 

http://www.linkedin.com/in/gbuehler/ 
Skype: gbuehler, Twitter: @ogc_greg 
Office: +1 812 334 0601 x701 / +1 202 810 4642 
Mobile: +1 812 327 6960 
gbuehler@opengeospatial.org 
www.opengeospatial.org/contact 

Keep up with all the OGC news by signing up to our quarterly newsletter at [ http://newsletter.opengeospatial.org/ | http://newsletter.opengeospatial.org ]

**Comment by gbuehler** [comment]
All,

We use the OGC license for documents. Should there also be code in this repo, most OGC GitHub projects use the Apache license for the code.

Scott

**Comment by gbuehler** [comment]
+1

**Comment by RichCarne** [comment]
Thanks @gbuehler the license looks compareable the the one I’ve committed. I’ll do a diff and check it’s right.

**Comment by RichCarne** [comment]
Thanks Greg, I’ll ensure we make use of the correct licence. And if we do include code then the apache licence to cover this.

Thanks all.

Rich.

Rich
________________________________

**Comment by chris-little** [comment]
I agree with Scott and Greg - as we are doing this under the auspices of OGC, the OGC Licence(s) are appropriate.

**Pull request merged**
